class SecurityAccessException(Exception):
    pass

class PerformanceException(Exception):
    pass

class InternalError(Exception):
    """
    This exception must be used to catch internal error generated by a lib
    This error should be catch only once by the error handle to avoid cyclic error
    """
    pass